### ISSUE TITLE
Lost vacuum cleaner

### ISSUE THREAD

**Issue by T0macher** [jghaanstra/com.xiaomi-miio#199] opened 2023-04-28 20:30 UTC
Hi,

Sorry for disturbing. I lost the connection with my vacuum cleaner after the last update.
The token and the IP address is ok.
<img width="930" alt="Screenshot 2023-04-28 at 22 28 38" src="https://user-images.githubusercontent.com/128604773/235248312-5548753a-7e1c-4ccd-a9eb-cc5bc2409488.png">

I made a diagnostic report: 85dee33c-a526-4274-a224-0cc40ba3b7c5

Could you please help me?

Thank you so much!
Tamas

**Comment by jghaanstra** [comment] 2023-04-28 20:51
The error says there is something wrong with the token.

```
2023-04-28T19:05:27.188Z [err] [Homey:6407146e7980200b7bd344ed] [ManagerDrivers] [Driver:vacuum_dreame_vacuum] [Device:e066606f-96c5-4cea-a6a6-e7eca1c87cb0] Could not connect to device, handshake timeout
2023-04-28T19:05:39.193Z [err] [Homey:6407146e7980200b7bd344ed] [ManagerDrivers] [Driver:vacuum_dreame_vacuum] [Device:e066606f-96c5-4cea-a6a6-e7eca1c87cb0] Could not connect to device, handshake timeout
2023-04-28T19:05:51.196Z [err] [Homey:6407146e7980200b7bd344ed] [ManagerDrivers] [Driver:vacuum_dreame_vacuum] [Device:e066606f-96c5-4cea-a6a6-e7eca1c87cb0] Could not connect to device, handshake timeout
2023-04-28T19:05:54.824Z [err] [Homey:6407146e7980200b7bd344ed] [ManagerDrivers] [Driver:vacuum_dreame_vacuum] [Device:e066606f-96c5-4cea-a6a6-e7eca1c87cb0] Could not connect to device, handshake timeout
```

Have you tried rebooting Homey and/or forcing a reconnect of the vacuum cleaner from the router. If so, you might need to reconnect it to the network to get a fresh token and re-add it to Homey.

As this is not a bug with the app but related to using an unofficial method of communication I'm closing this here. If you need further support please use the support forum.

**Closed by jghaanstra** 2023-04-28 20:51 UTC
