### ISSUE TITLE
Wake-up Philips bulbs

### ISSUE THREAD

**Issue by rdvanbuuren** [jghaanstra/com.xiaomi-miio#64] opened 2018-11-28 11:42 UTC
I'm having an issue with the Philips Bulbs. Whenever the lights are on or off for some time, they don't respond to the first on / off signal from a Homey flow. I'm having the same issue triggering them from the HomeKit app. When I send it multiple times (about 2-3), they'll eventually wake up and listen to the signal.

You seem to have added some kind of [polling mechanism](https://github.com/jghaanstra/com.xiaomi-miio/blob/c978cf3c21c56a0994ac1a009a4ad1535dcb5158/drivers/philips-bulb/device.js#L73) to check if the bulbs are online? The Mi Home app does something similar. It sends this signal every few seconds: `data= {"id":7300,"method":"get_prop","params":["power","bright","cct","snm","dv"]}` to read the device' status.

Does the following code in the polling mechanism trigger a signal to the bulb itself?
`const power = await this.miio.power();`
`const brightness = await this.miio.brightness();`
Or does it just read some status property from the library? In that case, wouldn't it be better to trigger the get_prop signal on the light itself?

**Comment by jghaanstra** [comment] 2018-11-28 11:51
My Homey app uses the miio library. This library is used to create a connection with a device that supports the miio protocol and create miio device instance which I use in my Homey app. The polling mechanism you mentioned is used to read out the device instance and get the actual data. The communication with the miio device is taken care of by the miio library. However, there is an issue with the miio library that causes this behaviour where the first request is not handled correctly. It has to do with some sort of caching mechanism. I have reported this in the miio library but it has not been completely resolved and it appears that it's no longer supported by the author. For more details see here:

https://github.com/aholstenson/miio/issues/94#issuecomment-360983227

I'll close this issue since it's a duplicate of: https://github.com/jghaanstra/com.xiaomi-miio/issues/27

**Closed by jghaanstra** 2018-11-28 11:51 UTC
