### ISSUE TITLE
Dockning mi robot

### ISSUE THREAD

**Issue by cop112** [jghaanstra/com.xiaomi-miio#49] opened 2018-09-03 15:48 UTC
Roborock s50 won’t dock thru flowcard or manually thru homey v2 app. App not showing correct state of vacuum white docked (shows cleaning instead of docked).

**Comment by jghaanstra** [comment] 2018-09-05 12:29
Release 2.8.2 will fix the docking action card. Incorrect state is probably caused by updates timing out. Is it always showing the incorrect state when docked or only sometimes?

https://github.com/jghaanstra/com.xiaomi-miio/releases/tag/2.8.2

**Comment by cop112** [comment] 2018-09-05 13:10
Mine is always showing "Cleaning" when docked. But someone in the fb-group said his is always showing "Charging" while docked even if device is fully charged.

**Comment by jghaanstra** [comment] 2018-09-05 15:19
I just tested this. It seems the V1 indeed always shows charging, unfortunately this seems to be a bug with the miio library. But I might have a work around where I also check if battery level. I'll see if this can be added to release 2.8.2.

**Comment by PeetersJan** [comment] 2018-09-09 09:26
The app keeps on crashing; any possibility to do a downgrade?
I have been searching to find the app.zip for the cli installation method, but cannot find the 2.8.0 anywhere. 2.8.0 (or .1) worked just fine for me.
Any chance you would share this?
Br,

**Comment by jghaanstra** [comment] 2018-09-09 13:14
I'm closing this issue. The docking action card has been fixed with release 2.8.2. Possible crash issues may have been resolved with 2.8.3 which is pending the app store. If not, please submit a bug after this has been tested. Not showing the correct state is probably due to time out issues.

**Closed by jghaanstra** 2018-09-09 13:14 UTC
