### ISSUE TITLE
All issues related to vacuum cleaners

### ISSUE THREAD

**Issue by blexter** [jghaanstra/com.xiaomi-miio#165] opened 2023-03-08 09:31 UTC
Would much appreciate the "Roomcleaning" feature to be implemented. 

This applies to (at least, probably many more models) Roborock S5
In the app provided by the manufacture (not Homey app, "phone"-app), there is an function to map your home and divide it in "Rooms", then its possible to clean a specific room.

In the "background" every room gets an Id which is possible to use when starting a Roomcleaning by API (or simular).
The "old" app "Roborock" (Homeyapp) has this feature and the function is solved by sending this "RoomId" as identifier for which room that should be cleaned.
See picture for instructions from the "old app".

![image](https://user-images.githubusercontent.com/37409960/223675369-e7648c67-588a-425a-8505-82204d64f1c9.png)

Feel free to reach out if any details is missing or so.

**Comment by shaarkys** [comment] 2023-03-08 10:30
If I may suggest, having also **coordinates** (go to coordinates) , that would be something useful as well - unfortunately not sure if the original app allowed it and also Roborock app, which supported that, the source code is not disclosed and original developer is pissed of on Athom, so he is probably even not willing to transfer source code ;-(  

The concept is explained here - "Going to target point:" - https://community.homey.app/t/app-pro-roborock-vacuum-cleaners/49521

Also Room ID is described in section "Find room ID’s for room cleanup"

As I'm also using ioBroker for information about cleaned value (parsing via MQTT and then then "full trash" sending to coordinated so I can clean the robot ;-) - so that integration might help to provide some insights...

https://github.com/iobroker-community-adapters/ioBroker.mihome-vacuum/blob/master/README.md


![obrazek](https://user-images.githubusercontent.com/14859895/223689122-acf48348-37f1-4769-b75d-73dd520902f3.png)

**Comment by shaarkys** [comment] 2023-03-08 10:31
If that would be added, you can count with another small coffee from me for sure ;-)  Yep, I know it doesn't mean anything, just inspiring others ;-)

**Comment by jghaanstra** [comment] 2023-03-08 19:03
The next release will add a "Clean Room" action card allowing to enter the room ID's which need to be cleaned. The driver voor the v1, 1S and S5 models and for the T6 model will have the current room ID's saved under the device settings. All is explained in further detail here: https://github.com/jghaanstra/com.xiaomi-miio/wiki/Vacuum-cleaners#using-the-clean-room-action-card

Everything is created without having a device to test with, limited documentation and limited understanding of how this should work  so please test it thoroughly.

I'll keep this ticket open as I'm not expecting it to work smoothly right away.

**Comment by shaarkys** [comment] 2023-03-08 19:16
I can test, but I have S6 :-)

**Comment by jghaanstra** [comment] 2023-03-08 19:19
> I can test, but I have S6 :-)

It will probably work with the v1, 1S, S5 driver.

**Comment by shaarkys** [comment] 2023-03-09 05:45
Thank you, almost there - after I added it, it start loading values but after a while :

d4dd21ee-ae43-4759-8da5-4e807c9dec59

**Comment by blexter** [comment] 2023-03-09 09:13
* I have tried the latest version, if I from "chargingposition" try to change to status "zone cleaning" nothing happens. If i start a "regualar" cleaning and than change to "zone cleaning" when the robot left the charging it possible to start. But not directly from charging position
* I tried to use the "room cleaning" function, but only found "start zone cleaning" (with parameter), that doesnt work as I wish.
Flow as attached picture. 
![image](https://user-images.githubusercontent.com/37409960/223975031-3b331785-b7d6-413f-84fa-b080e5efcc7a.png)

**Comment by shaarkys** [comment] 2023-03-09 09:16
@blexter please always include diag. code... (unless you sent it from the app already)

**Comment by jghaanstra** [comment] 2023-03-09 22:32
> Device is unreachable: invalid_setting_type

Hope to have fixed this in the next release.

> I have tried the latest version, if I from "chargingposition" try to change to status "zone cleaning" nothing happens. If i start a > "regualar" cleaning and than change to "zone cleaning" when the robot left the charging it possible to start. But not directly > from charging position
> I tried to use the "room cleaning" function, but only found "start zone cleaning" (with parameter), that doesnt work as I wish.
> Flow as attached picture.
Please re-pair your robot with the `Mi Roborock Vacuum v1 / 1s / s5` instead of the generic Mi Robot driver and test again on the new release (3.1.3).

**Comment by blexter** [comment] 2023-03-10 06:53
Seems I didnt got the robot docked yesterday, so its offline and not reachable now when im at work, so no updates from me (at least) coming 8h.

**Comment by shaarkys** [comment] 2023-03-10 07:32
> Hope to have fixed this in the next release.

THANK YOU - yep, it is...unfortunately there are some other issues (at least for S6).

**What works :** 
- STOPing vaccuum robot - via ON/OFF works but is not updated from the state of the device (in iOBroker under "state" / value.state)
- sending to DOCK
- values got updating - total cleared area, total clean count
- seems also WORK times (brushes) are updated

**What doesn't work**
- sending cleaner to coordinates - does nothing (seems to be Go.To function in iOBroker)
- DIM to action starts cleaning - also diming is probably Volume ? Still the Volume is not changing (checked in the ioBroker after modifying in Homey app)
![obrazek](https://user-images.githubusercontent.com/14859895/224242564-c5a5dc2e-7368-4eae-b061-88dc1f3231ad.png)
- set POWER do not work (robot sounds like accepting command but it visibly does nothing) - also checked in iOBroker, it did not modify the value of fun_power / level.suction
- status always shows CHARGING even when cleaning, even when battery fully charged and even when returning to DOCK
- room segments looks weird now after last update - see screenshot
- total work time is some strange value not updated - eg. see my vacuum, after 3 years it reports 9min ;-) (it's also not the last cleaning time, it was in my case 1min during testing) - but seems it's just calculated incorrectly from reported value of 9915 min ? (see ioBroker)
- Total area should be with m2 unit

![obrazek](https://user-images.githubusercontent.com/14859895/224249924-9cbcec68-f2f1-4f31-afae-d79697569192.png)

Diag > 71e8777c-fd1f-4b2c-887b-ca9947e059a7

Do you think you can include also **Error**, **Cleaned area** , **Mop** ? I can create eventually feature request - also make sense if it's easy to implement, not sure how the integration works and if my inputs from iOBroker actually have added value....

![obrazek](https://user-images.githubusercontent.com/14859895/224250909-5997a466-2aaa-44b2-95af-30c1e8020042.png)


IoBroker screenshot (ignore differences 1)
![obrazek](https://user-images.githubusercontent.com/14859895/224250210-dee782ec-c6fb-4e6a-8ac2-12297d02c864.png)

**Comment by jghaanstra** [comment] 2023-03-10 18:16
> sending cleaner to coordinates - does nothing (seems to be Go.To function in iOBroker)

Probably fixed with next release

> DIM to action starts cleaning - also diming is probably Volume ? Still the Volume is not changing (checked in the ioBroker after modifying in Homey app)

It's fan speed but that might not work for the S6 on this driver.

> set POWER do not work (robot sounds like accepting command but it visibly does nothing) - also checked in iOBroker, it did not modify the value of fun_power / level.suction

Sound specific to the S6 as well. This device is not supported (yet).

> status always shows CHARGING even when cleaning, even when battery fully charged and even when returning to DOCK

There is still something wrong with parsing vacuum statuses, this needs further investigation

> room segments looks weird now after last update - see screenshot

It's supposed to, see the Wiki on how to use it for getting the ID's for the room cleaning action card.

> total work time is some strange value not updated - eg. see my vacuum, after 3 years it reports 9min ;-) (it's also not the last cleaning time, it was in my case 1min during testing) - but seems it's just calculated incorrectly from reported value of 9915 min ? (see ioBroker)

I just copied this code from Mi Homey. Not gonna look into it now but removed conversion which suggests it was in milliseconds. For now it will report a raw value from the next release.

> Total area should be with m2 unit

I'll add it to the label, if added to the value I cant compare it as a numeric value anymore. Also copied code by the way.

**Comment by jghaanstra** [comment] 2023-03-10 18:35
> Do you think you can include also Error, Cleaned area , Mop ? I can create eventually feature request - also make sense if it's easy to implement, not sure how the integration works and if my inputs from iOBroker actually have added value....

Make seperate feature request, I'm first trying to make the app stable and not focus on new (for most users not very important) features.

**Comment by shaarkys** [comment] 2023-03-10 20:02
Hi,

ecb9c616-7689-46e7-9157-5b70eb1ce134

again Invalid settings type :-(

**Comment by jghaanstra** [comment] 2023-03-10 20:30
> again Invalid settings type :-(

Should be fixed with 3.1.7

**Comment by shaarkys** [comment] 2023-03-10 21:14
> sending cleaner to coordinates 
> Probably fixed with next release
> 

Fixed indeed, thx 3.1.7
 
> It's fan speed but that might not work for the S6 on this driver.

Strange, even original app didn't have FAN speed, also in IoBroker I see only states below. Let's see what S5 users will say.

  "type": "state",
  "common": {
    "name": "Suction power",
    "type": "number",
    "role": "level.suction",
    "read": true,
    "write": true,
    "min": 101,
    "max": 106,
    "states": {
      _"101": "QUIET",
      "102": "BALANCED",
      "103": "TURBO",
      "104": "MAXIMUM",
      "105": "OFF",
      "106": "CUSTOM"_
> 
> > status always shows CHARGING even when cleaning, even when battery fully charged and even when returning to DOCK
> 
> There is still something wrong with parsing vacuum statuses, this needs further investigation

Partially fixed in 3.1.7 - now when launched from APP, Robot does as required (Stop, Docks, start cleaning) etc.
I'm not sure though if when not charging anymore, if the state shall be still Charging and not Docked.

Also the states are not updated when launched directly from robot - eg. polling ? Diag. e8b29b8c-385d-4b76-8c06-90b7b7c347ce

> > room segments looks weird now after last update - see screenshot
> 
> It's supposed to, see the Wiki on how to use it for getting the ID's for the room cleaning action card.

Ah, OKay, never used it, I was just compering Room indexes from IoBroker integration, where I see it's "Integer" not Fraction ... if it's OKay, then perfect. ;-)

![obrazek](https://user-images.githubusercontent.com/14859895/224428475-1000d3ca-3b4c-4c5d-87da-4e00cd66ebb8.png)


> > total work time is some strange value not updated - eg. see my vacuum, after 3 years it reports 9min ;-) (it's also not the last cleaning time, it was in my case 1min during testing) - but seems it's just calculated incorrectly from reported value of 9915 min ? (see ioBroker)
> 
> I just copied this code from Mi Homey. Not gonna look into it now but removed conversion which suggests it was in milliseconds. For now it will report a raw value from the next release.

Raw value is OKay for me, even just simply dividing "Total work time" value by 60 will get minutes instead of seconds ;-) 

> 
> > Total area should be with m2 unit
> 
> I'll add it to the label, if added to the value I cant compare it as a numeric value anymore. Also copied code by the way.

Sure, I meant label only, same as total working time now in secs, but that's okay. **Thank you for everything !**

**Comment by jghaanstra** [comment] 2023-03-10 22:16
> I'm not sure though if when not charging anymore, if the state shall be still Charging and not Docked.

The vacuum doesnt have a charged state. If other integrations show the difference between charging and charged it has been manually implemented but this has never been added in the Mi Home or Mi Homey app.

**Comment by shaarkys** [comment] 2023-03-10 22:25
> doesnt have a charged state.

Just an idea - maybe battery = 100% --> charged ?

A pity that Justin is not willing to share his code...  (https://community.homey.app/t/app-pro-roborock-vacuum-cleaners/49521)

**Comment by jghaanstra** [comment] 2023-03-10 22:26
> Just an idea - maybe battery = 100% --> charged ?

Sure, but as mentioned for now I'm mostly porting the current code. New features is for later.

**Comment by shaarkys** [comment] 2023-03-10 22:34
> New features is for later.

I have updated the feature request also with some parts I found in MaxMudjon implementations, if it will later help anyhow or not, you will see. Thank you.

**Comment by shaarkys** [comment] 2023-03-10 22:39
> Sound specific to the S6 as well. This device is not supported (yet).

https://community.homey.app/t/app-pro-xiaomi-mi-home-app-for-wifi-devices/118/368?u=sharkys

;-) ~3 years ago you added it (still I don't know what was the difference, so rather take it as attempt for joke

**Comment by blexter** [comment] 2023-03-11 10:07
Testing on the S5:

My usecases seems to work now (primary - room cleaning)

What i outside that found thats a bit "sketchy",
* From charging position "Spotcleaning" cant start, gets error that i should move the robot to the spot first, seems to be as design of the robot?!
* Status Dock and Charge seems to do exact the same thing, at least for my robot.
* The onoff button status not seems to get updated if a status change was made
* Not sure what the "volume" slider does at all
* Dim to 50% set fanpower to "Balanced", but 100% doesnt change it at all. Not sure how/why this function works like this, might be "error" on me
* Set relative dim-level 50%, same as above.
* Set fan power only can set "Balanced" like the dim-behaviour above

I tested all availible cards, and that not mentioned above seems to work what i can understand.

**Comment by jghaanstra** [comment] 2023-03-11 10:49
> From charging position "Spotcleaning" cant start, gets error that i should move the robot to the spot first, seems to be as design of the robot?!

Yes, that's how it works.

> Status Dock and Charge seems to do exact the same thing, at least for my robot.

Correct, both will send the robot back to the dock. Its related to the weird implementation of the vacuumcleaner_state capability in Homey where you can set the state to docked (which is not an active state to assign on the vacuum cleaner)

> The onoff button status not seems to get updated if a status change was made

Hope to have improved this on the next release.

> Not sure what the "volume" slider does at all
> Dim to 50% set fanpower to "Balanced", but 100% doesnt change it at all. Not sure how/why this function works like this, might be "error" on me
> Set relative dim-level 50%, same as above.
> Set fan power only can set "Balanced" like the dim-behaviour above

It's was implemented by the previous developer and is supposed to set the fanspeed but it's very inconsistent. I might remove it all together.

**Comment by jghaanstra** [comment] 2023-03-11 17:55
Version 3.1.8 contains a rewrite of the vacuumcleaner, please re-test.

> Breaking change: Completely reworked the code for the vacuum cleaners. This means devices that where paired after the release of version 3.1.0. Need to be repaired. You can choose between a basic vacuum cleaner driver that should support most cleaners and an advanced driver that should support more advanced models. Please test and report on Github.

**Comment by shaarkys** [comment] 2023-03-11 22:39
From mobile, sorry to be brief

S6 Roborock, added as advanced Wifi

👍
- fanspeed works
- states seems to be updated (not at home), including charging and docked, perfect

😞
- filters alarm not
- detailed data not (cleaned area etc)


Diag : 937e3fee-bb94-4870-87e9-c7abfc0b478f
(old devices not removed yet because of the flows repair required)

pictures like on : 
https://community.homey.app/t/app-pro-xiaomi-mi-home-app-for-wifi-devices/118/1085?u=sharkys

**Comment by jghaanstra** [comment] 2023-03-12 19:14
All the above should be fixed with the next release (3.1.9). Please let me know if there are more issues with the vacuum cleaner or if this ticket can be closed.

**Comment by shaarkys** [comment] 2023-03-12 20:17
Just minor one, still kind of enhancement related - https://github.com/jghaanstra/com.xiaomi-miio/issues/173#issuecomment-1465289835

Also tested re-added Goto coordinates and it works fine for me, thank you.

**Comment by blexter** [comment] 2023-03-13 10:08
Find one thing, my status;
Sensors dirty remaining says -110% (a warning/notice in Xiaomi iphone app).
It in the device view says Sensor Alert: No

6430ddbc-b6ed-4dd3-b296-c1dc7a54c8ce

![image](https://user-images.githubusercontent.com/37409960/224670591-119ac55b-e602-4484-9665-269f639be5b8.png)
![image](https://user-images.githubusercontent.com/37409960/224670659-89655cb8-7982-4498-a658-b2e83f85918e.png)

**Comment by jghaanstra** [comment] 2023-03-13 18:02
> Find one thing, my status; Sensors dirty remaining says -110% (a warning/notice in Xiaomi iphone app). It in the device view says Sensor Alert: No
> 
> 6430ddbc-b6ed-4dd3-b296-c1dc7a54c8ce

Should be fixed with the next release (3.1.10).

**Comment by blexter** [comment] 2023-03-14 07:21
Seems the same "error" there. Restarted the app and also delete/readded the device to "force" update.

1ed8509b-74df-41a9-a652-e7a4cd59b3d1

![image](https://user-images.githubusercontent.com/37409960/224924912-bcd981f9-579d-4d5c-9c4b-014f38f41d39.png)
![image](https://user-images.githubusercontent.com/37409960/224924995-7c9d349a-5a49-4265-b23f-c7bf633c7f9b.png)

**Comment by jghaanstra** [comment] 2023-03-14 18:18
> Seems the same "error" there. Restarted the app and also delete/readded the device to "force" update.
> 
> 1ed8509b-74df-41a9-a652-e7a4cd59b3d1
> 
> ![image](https://user-images.githubusercontent.com/37409960/224924912-bcd981f9-579d-4d5c-9c4b-014f38f41d39.png) ![image](https://user-images.githubusercontent.com/37409960/224924995-7c9d349a-5a49-4265-b23f-c7bf633c7f9b.png)

Hopefully fixed with the next release (3.1.12).

**Comment by blexter** [comment] 2023-03-15 07:49
Havnt tried "everything" again, by the "warning" part (above) is now solved.

**Comment by jghaanstra** [comment] 2023-03-15 08:21
Thanx, I'm closing this now.

**Closed by jghaanstra** 2023-03-15 08:21 UTC
Labels: waiting for input, feature

**Comment by blexter** [comment] 2023-03-15 09:06
Thank you so much!!

**Comment by Gizmopower1** [comment] 2023-03-24 08:12
Is s6 maxv Supported?

**Comment by jghaanstra** [comment] 2023-03-24 08:23
> Is s6 maxv Supported?
> I get an handshake error when trying to connect

It is, handshake error means incorrect token is used.

**Comment by Gizmopower1** [comment] 2023-03-24 08:28
The token is right. Works with Roborock app. 
Will try again now that you have confirmed that it works.

Thank you!
