### ISSUE TITLE
Roborock - Error, Cleaned area , Mop states + charging/docked state

### ISSUE THREAD

**Issue by shaarkys** [jghaanstra/com.xiaomi-miio#173] opened 2023-03-10 20:55 UTC
Do you think you can include also Error, Cleaned area , Mop ? I can create eventually feature request - also make sense if it's easy to implement, not sure how the integration works and if my inputs from iOBroker actually have added value....

https://github.com/jghaanstra/com.xiaomi-miio/issues/165#issuecomment-1463390383 (Io.Broker screenshot)

**Comment by shaarkys** [comment] 2023-03-10 22:31
https://github.com/Maxmudjon/com.maxmudjon.mihomey/blob/master/drivers/mi_rockrobo_vacuum_s5/device.js

 this.vacuumStates = {
      1: "Starting",
      2: "Charger disconnected",
      3: "Idle",
      4: "Remote control active",
      5: "Cleaning",
      6: "Returning home",
      7: "Manual mode",
      8: "Charging",
      9: "Charging problem",
      10: "Paused",
      11: "Spot cleaning",
      12: "Error",
      13: "Shutting down",
      14: "Updating",
      15: "Docking",
      16: "Going to target",
      17: "Zoned cleaning",
    };
    this.vacuumErrorCodes = {
      0: "No error",
      1: "Laser distance sensor error",
      2: "Collision sensor error",
      3: "Wheels on top of void, move robot",
      4: "Clean hovering sensors, move robot",
      5: "Clean main brush",
      6: "Clean side brush",
      7: "Main wheel stuck?",
      8: "Device stuck, clean area",
      9: "Dust collector missing",
      10: "Clean filter",
      11: "Stuck in magnetic barrier",
      12: "Low battery",
      13: "Charging fault",
      14: "Battery fault",
      15: "Wall sensors dirty, wipe them",
      16: "Place me on flat surface",
      17: "Side brushes problem, reboot me",
      18: "Suction fan problem",
      19: "Unpowered charging station",
    };
  
            if (result[0]["state"] == 5) {
              this.updateCapabilityValue("vacuumcleaner_state", "cleaning");
            } else if (result[0]["state"] == 11) {
              this.updateCapabilityValue("vacuumcleaner_state", "spot_cleaning");
            } else if (result[0]["state"] == 15) {
              this.updateCapabilityValue("vacuumcleaner_state", "docked");
            } else if (result[0]["state"] == 8) {
              this.updateCapabilityValue("vacuumcleaner_state", "charging");
            } else if (result[0]["state"] == 10) {
              this.updateCapabilityValue("vacuumcleaner_state", "stopped");

**Comment by jghaanstra** [comment] 2023-03-10 22:34
I'm aware of this but I fail to see how it relates to this feature request.

**Comment by shaarkys** [comment] 2023-03-10 22:41
It's partially only - Errors... and the Charging/Docked states.

**Comment by jghaanstra** [comment] 2023-03-12 19:11
- Errorcode : implemented with the next release (3.1.9)
- Mop intensity: implemented as custom capability under advanced driver if device supports it
- Charging  / Docked differentiation: implemented with the last release.

Please close this issue after successful testing or elaborate on what more is requested.

**Comment by shaarkys** [comment] 2023-03-12 20:16
Thank you, looks great. I just tested latest version, it's almost perfect, just few small things : 
- error code seems to be updated, tested two events - unfortunately there is no trigger for error state nor any variable error would be stored in, can you please add them ?
- when error reported, robot shall update it's state to STOPPED I guess (looks it remains in last command)
- could be total cleaned area m2 and clean count populated into variable ? (can be used to track down trash bin full events)

Can't test MOP intensity as S6 do not support it, so hopefully 

Diag if needed : cdf42784-94c9-4001-a442-f17566f5a8c4

**Comment by jghaanstra** [comment] 2023-03-12 21:12
> error code seems to be updated, tested two events - unfortunately there is no trigger for error state nor any variable error would be stored in, can you please add them ?

The `Status has changed` trigger card will be trigger upon error including the error as description as status token.

> when error reported, robot shall update it's state to STOPPED I guess (looks it remains in last command)

Will add that.

> could be total cleaned area m2 and clean count populated into variable ? (can be used to track down trash bin full events)

Not for now, I really want to focus on upgrading existing functionality. I'm already adding too much new stuff which I never promised to do.

**Comment by shaarkys** [comment] 2023-03-12 21:57
> Not for now, I really want to focus on upgrading existing functionality. I'm already adding too much new stuff which I never promised to do.

I understand, I just thought it might be last easy step to add...nevermind, will have to continue relying on ioBroker integration then, thank you.

**Comment by jghaanstra** [comment] 2023-03-13 20:59
Added with the latest release (3.1.11). Please confirm and close the ticket when OK.

**Comment by shaarkys** [comment] 2023-03-13 21:42
I apologize if I missed anything but I don't see anywhere cleaned area m2, clean count - do I have to re-add my Roborock devices ? Thank you.

![obrazek](https://user-images.githubusercontent.com/14859895/224838270-11cd6116-b25a-46f6-8243-de75bef1e42f.png)
![obrazek](https://user-images.githubusercontent.com/14859895/224838282-605cdac9-229f-460e-aa1f-e196ca70ce3b.png)

**Comment by jghaanstra** [comment] 2023-03-13 22:05
These are global tokens, look under the app, not under the device.

**Comment by shaarkys** [comment] 2023-03-13 22:19
Thank you. First I didn't understand what you mean but found it... so in case of more devices, those values always represent the last which was updating it? Please also note I got error now when trying to start cleaning - error Missing capability listener - diag. f8308ccc-f976-4d54-af40-a8b0cc5fad39

![obrazek](https://user-images.githubusercontent.com/14859895/224844730-977588fd-0453-4ee4-8078-3fd85db23901.png)

**Comment by jghaanstra** [comment] 2023-03-14 17:43
I'll add the name of the device they belong to. The issue is also related to users with more than one vacuum cleaner paired. Will be fixed in the next release (3.1.12).

**Comment by shaarkys** [comment] 2023-03-14 21:20
All seems to be fine, including global tokens per device - great job, thank you so much, I can now get rid of IoBroker for Roborocks and you FULLY replaced now for me the original Roborock app.

**Closed** 2023-03-14 21:20 UTC
Labels: waiting for input, feature
