### ISSUE TITLE
Mi Philips EyeCare 2 can't added

### ISSUE THREAD

**Issue by timas007** [jghaanstra/com.xiaomi-miio#28] opened 2018-04-13 18:42 UTC
![2018-04-13 22 35 02](https://user-images.githubusercontent.com/18547700/38752596-d3e01ff0-3f6c-11e8-828c-213cdfc7cc4a.png)
Philips EyeCare connected desk lamp gen.2 while trying to add in Athom Homey. The token and IP are correct.
What to do?

**Comment by AlexVVVx** [comment] 2018-04-17 12:38
Same error message. I have some technical skills but that would be good to have exact instructions. What command whould you like me to try?

**Comment by timas007** [comment] 2018-04-17 13:26
@AlexVVVx I just need to connect it.

**Comment by jghaanstra** [comment] 2018-04-17 16:33
@AlexVVVx install nodejs and the miio command line (npm install -g miio)

Go to your nodejs directory and create a file called miio.js which contains the following:
```
const miio = require('./node_modules/miio/lib');

// Create a new device over the given address
miio.device({
	address: '192.168.0.1',
  token: 'xxxxxxxxxxxxxxxxxxxxxxx'
}).then(device => {
  const getData = async () => {
      try {
          const power = await device.power();
          const brightness = await device.brightness()
          const mode = await device.mode();
          const eyecare = await device.eyeCareMode();

          let result = {
              onoff: power,
              brightness: brightness,
              mode: mode,
              eyecare: eyecare
          }

          console.log(result)
      } catch (error) {
          console.log(error);
      }
  }
  getData();
}).catch(err => console.log('Error occurred:', err));
```

Edit the path to where you installed miio, the IP address of your bulb and your token. Then run the script with node miio.js and let me know the output.

**Comment by AlexVVVx** [comment] 2018-04-17 17:17
@jghaanstra thanks for the details
Here is what I got:

pi@iobroker:~ $ sudo node miio.js
/home/pi/miio.js:8
  const getData = async () => {
                        ^

SyntaxError: Unexpected token (
    at createScript (vm.js:56:10)
    at Object.runInThisContext (vm.js:97:10)
    at Module._compile (module.js:549:28)
    at Object.Module._extensions..js (module.js:586:10)
    at Module.load (module.js:494:32)
    at tryModuleLoad (module.js:453:12)
    at Function.Module._load (module.js:445:3)
    at Module.runMain (module.js:611:10)
    at run (bootstrap_node.js:387:7)
    at startup (bootstrap_node.js:153:9)**

my code update: 
const miio = require('/usr/lib/node_modules/miio/lib');

// Create a new device over the given address
miio.device({
	address: '192.168.1.39',
  token: '58dceeaf1ce0beb17f301a33eefe3687'
}).then(device => {

**Comment by jghaanstra** [comment] 2018-04-17 19:06
I just tested the code, there is nothing wrong with it. My guess is you did not copy the complete code. Something else might be your nodejs version. Are you running at least nodejs 8.x?

**Comment by jghaanstra** [comment] 2018-04-17 21:12
For proper testing purposes it would be good to upgrade nodejs to version 8.x. I really cant explain the error in the test script otherwise.

You where able to retrieve the token for the light using one of the token recovery methods? Using the test script should tell more about what is going on.

**Comment by AlexVVVx** [comment] 2018-04-18 07:40
Ok. I will upgrade nodejs and test it again this evening. 
Yes, yesterday I started from token obtaining for lamp and humidifier. Method 1 showed the only token for humidifier so I had to use Method 2 to obtain the token for my lamp.

**Comment by AlexVVVx** [comment] 2018-04-18 17:06
@jghaanstra It looks like node upgrade helped. I have new error message now.
Please have a look.

pi@iobroker:~ $ node -v
v8.11.1

pi@iobroker:~ $ node miio.js
Error occurred: { Error: Could not connect to device, handshake timeout
    at Timeout.handshakeTimeout.setTimeout [as _onTimeout] (/usr/lib/node_module                                             s/miio/lib/network.js:427:17)
    at ontimeout (timers.js:482:11)
    at tryOnTimeout (timers.js:317:5)
    at Timer.listOnTimeout (timers.js:277:5) code: 'timeout', device: null }
pi@iobroker:~ $

**Comment by AlexVVVx** [comment] 2018-04-18 17:26
New error message after next try:

pi@iobroker:~ $ node miio.js
Error occurred: { TypeError: this.setModes is not a function
    at new EyecareLamp2 (/usr/lib/node_modules/miio/lib/devices/eyecare-lamp2.js:68:8)
    at network.findDeviceViaAddress.then.device (/usr/lib/node_modules/miio/lib/connectToDevice.js:25:12)
    at <anonymous> device: null }

**Comment by jghaanstra** [comment] 2018-04-18 19:41
Well, that confirms there is an issue with the miio library. I have submitted a bug there, there is not much else I can do as my own coding skills are limited and I dont own the device.

https://github.com/aholstenson/miio/issues/145

**Comment by AlexVVVx** [comment] 2018-04-18 20:05
@jghaanstra  Thank you

**Comment by timas007** [comment] 2018-04-19 16:31
> Error occurred: { TypeError: this.setModes is not a function
@AlexVVVx this is my mistake too.

**Comment by AlexVVVx** [comment] 2018-04-19 17:00
@timas007  yes, the error is reproduced and the bug is reported so the only we can do is to wait.

**Comment by jghaanstra** [comment] 2018-09-18 17:36
Support for this device has been removed since the underlaying miio library does not properly support it. Perhaps in the future it will return but for now I'm closing this issue.

**Closed by jghaanstra** 2018-09-18 17:36 UTC
Labels: bug, miio
