### ISSUE TITLE
Xiaomi Gateway v2 mode selector do not work on web app

### ISSUE THREAD

**Issue by shaarkys** [jghaanstra/com.xiaomi-miio#163] opened 2023-03-08 09:07 UTC
![obrazek](https://user-images.githubusercontent.com/14859895/223670390-beb2fc95-7ebb-4fd3-b8de-fc873c798d32.png)
![obrazek](https://user-images.githubusercontent.com/14859895/223670583-97558b05-53d8-454b-8216-74105de4ae3f.png)

...it works though via mobile phone app ?

**Comment by jghaanstra** [comment] 2023-03-08 12:07
This appears to be a bug in Homey SDK. This card is auto generated by the homealarm_state capability. I dont know why there is a device selection field. Raised a question in the Slack developer channel to get so more info.

**Comment by jghaanstra** [comment] 2023-03-11 13:40
This will be fixed in Homey SDK in the next couple of weeks. Closing it here as it's not a bug in this app.

See https://github.com/athombv/node-homey-lib/blob/master/assets/capability/capabilities/homealarm_state.json

**Closed by jghaanstra** 2023-03-11 13:40 UTC
Labels: waiting for input, needs research
