### ISSUE TITLE
Xiaomi smart humidifier unavailable

### ISSUE THREAD

**Issue by sam1kn** [jghaanstra/com.xiaomi-miio#249] opened 2023-11-01 11:55 UTC
After connecting zhimi.humidifier.cb1 to Homey right away I get “Device is unreachable: Invalid json.” Diagnostics b9538c06-b1f6-495e-ac87-af816da294dc

**Comment by jghaanstra** [comment] 2023-11-01 11:57
Seems like a user error and not a bug. Closing this for now.

**Closed by jghaanstra** 2023-11-01 11:57 UTC
