### ISSUE TITLE
Aqara hub v2 or v3

### ISSUE THREAD

**Issue by ENhomey** [jghaanstra/com.xiaomi-miio#114] opened 2019-11-19 12:53 UTC
I have an "Aqara hub v3" and also have the message "device.illuminance is not a function". Is the app only for the v2 gateway or also for the V3?

**Comment by jghaanstra** [comment] 2019-11-19 17:58
My app has only been tested with the Gateway v2 since I do not own a Gateway v3 myself. I need some extra info to be able to look into this and solve the issue. When and where exactly do you see this error.

(And please do not use the reviews in the app store for reporting bugs or requesting support for devices as these reviews are not updated once the bug is fixed or support has been added).

**Comment by jghaanstra** [comment] 2019-11-19 18:10
I have made some changes that might fix it and pushed these changes to the master branch on GitHub. Do you know how to run the app using the command line (as described here: https://community.athom.com/t/how-to-cli-install-method/198) to test this?

**Comment by ENhomey** [comment] 2019-11-20 07:57
I see the error at the screen where you enter the ip address and the token. after i have used the "test connection" button. I have no cli experience. But if you want, I can send the Hub to you.

**Comment by jghaanstra** [comment] 2019-11-20 08:18
Could you test it using this test version: https://homey.app/nl-nl/app/com.xiaomi-miio/Xiaomi-Mi-Home/test/

**Comment by ENhomey** [comment] 2019-11-20 08:53
Now I get the message "Cannot read property 'brightness' or undefined

Op wo 20 nov. 2019 om 09:18 schreef Jelger Haanstra <
notifications@github.com>:

**Comment by jghaanstra** [comment] 2019-11-20 09:12
Ok, I changed something. Could you try again.

https://homey.app/nl-nl/app/com.xiaomi-miio/Xiaomi-Mi-Home/test/

**Comment by ENhomey** [comment] 2019-11-20 10:19
Still the same message. "Cannot read property 'brightness' of undefined

Op wo 20 nov. 2019 om 10:12 schreef Jelger Haanstra <
notifications@github.com>:

**Comment by jghaanstra** [comment] 2019-11-20 11:19
Could you first check the version number you are running and then try again installing this version.

https://homey.app/nl-nl/app/com.xiaomi-miio/Xiaomi-Mi-Home/test/

**Comment by ENhomey** [comment] 2019-11-20 12:57
I was running version 2.13.5, i installed version  2.13.7 and now get the
message "Timed out after 30000ms"

Op wo 20 nov. 2019 om 12:19 schreef Jelger Haanstra <
notifications@github.com>:

**Comment by jghaanstra** [comment] 2019-11-20 13:01
Are you sure your token is correct?

**Comment by ENhomey** [comment] 2019-11-20 15:23
I extracted Token again. and it's the same. I have reset the homey. and
added the hub via the iphone. then i get the message "timed out after
30000ms"
If I add the hub via the developer site, I get the message "Network request
failed" also strange.

Op wo 20 nov. 2019 om 14:01 schreef Jelger Haanstra <
notifications@github.com>:

**Comment by jghaanstra** [comment] 2019-11-20 18:37
I just tested my own Gateway v2 after I updated to the latest firmware. I cant connect it as well. It seems Xiaomi is actively preventing it from connecting. I need to investigate this further.

**Comment by jghaanstra** [comment] 2019-11-20 18:49
Ok, looks like the method with the token has become obsolete. I'm currently looking into merging the Xiaomi Mi Home app with another developer that has a different implementation that also support the gateway subdevices. 

I'm keeping this issue open but I wont be fixing it for now.

**Comment by ENhomey** [comment] 2019-11-20 19:28
Ok then I'll wait until there is an app that also incorporates the hub v3.
Thanks for the effort.

Op wo 20 nov. 2019 om 19:49 schreef Jelger Haanstra <
notifications@github.com>:

**Comment by KrakenTyio** [comment] 2019-12-02 21:04
I can confirm all states with correct token was occurent on my gateway

Is this another developer from Mi Homey project?
Are you creating some merge app sollution? Bc. mi Homey is still not available on homey app store

**Comment by jghaanstra** [comment] 2019-12-02 21:10
I offered to hand over ownership of the Xiaomi Mi Home app to the developer of the Mi Homey app. He is considering it but is still talking with Athom to have his own app publised next to mine (which is probably not going to happen as they are to similar).

**Comment by KrakenTyio** [comment] 2019-12-02 21:51
Thx to answer, probably merge project as one and maintaining functions with and without gateway simultanously
But this is only suggestions

**Comment by Sjuul70** [comment] 2019-12-24 13:36
I assume a password is required to be able to pair the hub with Homey. Model: lumi.gateway.v3

![Screenshot_20191224-134250_Mi Home](https://user-images.githubusercontent.com/54183800/71414756-a37bd280-2658-11ea-957a-6a0d981c9a94.jpg)
![Screenshot_20191224-133924_Homey](https://user-images.githubusercontent.com/54183800/71414757-a37bd280-2658-11ea-9357-1c9f0ea70869.jpg)

**Comment by jghaanstra** [comment] 2019-12-24 16:45
Not as it was initially coded. But that does not seem to work anymore. I'm about to remove support of the gateway from the Xiaomi Mi Home app.

**Closed by jghaanstra** 2019-12-24 16:45 UTC
Labels: bug, waiting for user input
